name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log file structure
        run: |
          echo "Logging complete file structure:"
          find . -type f | sort
          echo "Detailed structure:"
          ls -laR

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-node-sample-project:latest

  deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Initialize Docker Swarm
        run: docker swarm init || true

      - name: Log file structure
        run: |
          echo "Finding stack-deploy.yml file..."
          find . -name "stack-deploy.yml"
          echo "Logging complete file structure:"
          find . | sort

      - name: Deploy to Docker Swarm
        run: |
          docker network create --driver overlay app-network || true
          docker stack deploy -c ./stack-deploy.yml docker-test