name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug file structure
        run: |
          echo "Listing all files in workspace:"
          find . | sort

      - name: Find stack-deploy.yml
        run: find . -name "stack-deploy.yml"

      - name: Initialize Docker Swarm
        run: docker swarm init || true

      - name: Deploy to Docker Swarm
        run: |
          docker network create --driver overlay app-network || true
          docker stack deploy -c ./stack-deploy.yml docker-test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Initialize Docker Swarm
        run: docker swarm init || true

      - name: Find stack-deploy.yml
        run: find . -name "stack-deploy.yml"

      - name: Log file structure
        run: |
          echo "Logging complete file structure:"
          find . -type f | sort
          ls -laR

      - name: Deploy to Docker Swarm
        run: |
          docker network create --driver overlay app-network || true
          docker stack deploy -c ./stack-deploy.yml docker-test
